### ISSUE TITLE
NavChallenge empty route

### ISSUE THREAD

**Issue by pkohout** [robocup-logistics/rcll-refbox#105]
We tested the NavChallange today for the first time, the refbox sends only an empty route, we used the branch `neltester/challenges-2021` for our testing.

Log output of the received route, one route is created but it does not contain anything. We are in the Production Phase (afaik the routes are only send during Production or?)
```
2021-06-03 15:25:00.089  INFO 11225 --- [       Thread-9] c.g.r.m.NavigationChallangeHandler       : Got navigationoRoutes: team_color: MAGENTA
routes {
  id: 1
}

```
our refbox config: 
```
  # navigation easy
  challenges:
    enable: true
    name: "nav_easy"
    # max is 7 x 8
    field:
      width: 5
      height: 5
      # if true this effectively doubles the field size
      mirror: false
    # Phases in which the machine positions are broadcasted
    send-mps-ground-truth: []

    production-time: 1020
    orders:
      # if disabled, use default orders from rcll
      customize: false
      # each order is nvamed O<INTEGER>
      O1:
        base-color: BASE_RED
        ring-colors: [RING_BLUE, RING_YELLOW, RING_ORANGE]
        cap-color: CAP_BLACK
    publish-routes:
      enable: true
      num-points: 12
      num-routes: 1
      pause-duration: 5
```
